language: java
os:
  - linux

matrix:
  fast_finish: true

  include:
    # JDK 8
    - jdk: openjdk8

    # JDK 9
    - jdk: openjdk9

    # JDK 10
    - jdk: openjdk10

    # JDK 11
    - jdk: oraclejdk11
